belulProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
admin.autodiscover()
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.flatpages.views import *
from . import views

admin.site.site_header = settings.ADMIN_SITE_HEADER



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.mainView, name='mainPage'),
    url(r'^', include('connect.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^company/about/', flatpage, {'url':'/company/about/'}, name='about'),
    url(r'^company/goods/', flatpage, {'url':'/company/goods/'}, name='goods'),
    url(r'^company/park/', flatpage, {'url':'/company/park/'}, name='avtopark'),
    url(r'^stations/adresses/', flatpage, {'url':'/stations/adresses/'}, name='adresa'),
    url(r'^stations/services/', flatpage, {'url':'/stations/services/'}, name='uslugi'),
    url(r'^sale/conditionterms/', flatpage, {'url':'/sale/conditionterms/'}, name='postavka'),
    url(r'^sale/shipping/', flatpage, {'url':'/sale/shipping/'}, name='dostavka'),
    url(r'^contacts/', flatpage, {'url':'/contacts/'}, name='contacts'),
    url(r'^', include('article.urls')),
    url(r'^', include('price.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

# /venv/lib/python2.7/site-packages/django/contrib/admin/static/admin

connect/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from connect import views


urlpatterns = [
    url(r'^connect/', views.connect, name='connect'),
    url(r'^thank-you/', views.thanks),
]

price/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from price import views



urlpatterns = [
    # url(r'^prices/$', views.prices, name='prices'),
	url(r'^prices/$', views.PriceView.as_view(), name='prices'),
	# url(r'^prices/priceladoga/$', views.priceladoga),
    # url(r'^prices/price/$', views.price, name='price'),

]

connect/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class Connect(models.Model):
	connect_firstname = models.CharField(max_length=15, verbose_name = 'Имя')
	connect_lastname = models.CharField(max_length=15, verbose_name = 'Фамилия')
	connect_mail = models.EmailField(max_length=120, verbose_name = 'E-mail')
	connect_phonenumber = models.IntegerField(verbose_name = 'Номер телефона')
	connect_text = models.TextField(blank=True, verbose_name = 'Сообщение')

	class Meta():
		db_table = 'connect'
		verbose_name = 'Обратная связь'
		verbose_name_plural = 'Обращения от пользователей'

	def __unicode__(self):
		return "%s %s" % (self.connect_lastname, self.connect_firstname)

connect/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from .models import *

class ConnectForm(forms.ModelForm):
	class Meta():
		model = Connect
		exclude = ['']
		error_messages = {'connect_mail': {'required': 'Введите E-mail в формате example@example.com'}, 'connect_phonenumber': {'required':'Введите номер в формате 79211234567 или 8121234567'}}

connect/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from .forms import ConnectForm
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.core.paginator import Paginator
from article.models import Article

# from django.template.context_processors import csrf

# Create your views here.


def connect(request):	
	form = ConnectForm(request.POST)
	if request.method == 'POST' and form.is_valid():
		form.cleaned_data
		new_form = form.save()
		return HttpResponseRedirect('/thank-you/')
	else:
		return render(request, 'connect.html', locals())


# def thanks(request):
# 	return render_to_response('thanks.html')

def thanks(request, page_number=1):
	all_articles = Article.objects.all()
	current_page = Paginator(all_articles, 2)
	return render_to_response('thanks.html', {'thanks': current_page.page(page_number)})

connect/templates/connect.html
{% extends 'main.html' %}
{% load staticfiles %}
{% block connect %}
	<div class="container containerArt">
		<div class="col-md-9 colArt">
			<div class="row rowArt">
				<article>
					<form action="#" method="post">{% csrf_token %}
						<div class="connection">
						<p class="lead mLead">ОБРАТНАЯ СВЯЗЬ</p>
						<p class="pSmall"><small>Если у вас имеются вопросы, оставьте свои контакты и мы обязательно свяжемся с Вами!</small></p>

							<div class="row rowConnect">
								<label class="col-md-3 fixedCol" for="id_connect_lastname">Фамилия:</label>
								<div class="col-md-9"> 
									<input type="text" class="form-control" name="{{ form.connect_lastname.name }}">

								</div>
							</div>
							<div class="row rowConnect">
								<label class="col-md-3 fixedCol" for="id_connect_firstname">Имя:</label>
								<div class="col-md-9"> 
									<input type="text" class="form-control" name="{{ form.connect_firstname.name }}">

								</div>
							</div>
							<div class="row rowConnect">
								<label class="col-md-3 fixedCol" for="id_connect_mail">E-Mail:</label>
								<div class="col-md-9"> 
									<input type="text" class="form-control" name="{{ form.connect_mail.name }}">
									{{ form.connect_mail.errors }}
								</div>
							</div>
							<div class="row rowConnect">
								<label class="col-md-3 fixedCol" for="id_connect_phonenumber">Телефон:</label>
								<div class="col-md-9"> 
									<input type="text" class="form-control" name="{{ form.connect_phonenumber.name }}">
									{{ form.connect_phonenumber.errors }}
								</div>
							</div>
							<div class="row rowConnect">
								<label class="col-md-3 fixedCol" for="id_connect_text">Сообщение:</label>
								<div class="col-md-9"> 
									<textarea class="form-control" rows="7" name="{{ form.connect_text.name }}"></textarea>
								</div>
							</div>

							<div>
							<button type="submit" class="btn btn-primary">Отправить</button>
							</div>
						</div>

					</form>
				</article>
			</div>
		</div>
	</div>
{% endblock %}

connect/templates/thanks.html
{% extends 'sidebar.html' %}
{% load staticfiles %}

{% block thanks %}
<div class="col-md-8 colArt">
	<div class="row rowArt">
		<article>
			<div class="col-md-8 col-md-offset-2">
				<p class="text-center lead">Спасибо за Ваше обращение, мы обязательно ответим Вам в ближайшее время! :)</p>
			</div>
		</article>
	</div>
</div>
{% endblock %}